name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      multiple: false
      options:
        - macOS Monterey (12.x)
        - macOS Ventura (13.x)
        - macOS Sonoma (14.x)
        - macOS Sequoia (15.x)
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: ex. v1.0.0
    validations:
      required: true
